### ISSUE TITLE
I can't start, got error code 3 connecting routing system

### ISSUE THREAD

**Issue by tbiancoar** [VROOM-Project/vroom-docker#25]
I followed the steps and build my test in https://api-vroom.cr.onway.app/

But when I try with test request sometimes I got (using VROOM_ROUTER="ors"): 

2020-11-06T13:05:18.465245743Z Fri, 06 Nov 2020 13:05:18 GMT: [Error] 
2020-11-06T13:05:18.465584149Z Fri, 06 Nov 2020 13:05:18 GMT: Failed to connect to 0.0.0.0:5000
2020-11-06T13:05:18.465862641Z Fri, 06 Nov 2020 13:05:18 GMT: 

Changing enviroment variables and using (VROOM_ROUTER="osrm") I got: 

2020-11-06T13:12:49.048898242Z Fri, 06 Nov 2020 13:12:49 GMT: [Error] 
2020-11-06T13:12:49.049249511Z Fri, 06 Nov 2020 13:12:49 GMT: Invalid profile: car.
2020-11-06T13:12:49.049500938Z Fri, 06 Nov 2020 13:12:49 GMT: 

Any help?

**Comment by nilsnolde** [comment]
full docker-compose pls? also the `conf/config.yml` in case you changed anything..

**Comment by tbiancoar** [comment]
I don't use docker-compose, I use dockerFile.

I didn't changed config file.

**Comment by nilsnolde** [comment]
this is not reproducible for me.. you're using default here. meaning `osrm`, which expects `profile: car` (or other osrm profile, see [here](https://github.com/VROOM-Project/vroom-express/blob/master/config.yml)).

do you have osrm or ors available on that machine?

**Comment by nilsnolde** [comment]
with that config, what's the failing request then?

**Comment by tbiancoar** [comment]
how i can check if OSRM is up in docker?

**Comment by nilsnolde** [comment]
not sure what you mean here.. did you explicitly start a OSRM instance?

**Comment by tbiancoar** [comment]
how i can check in container if OSRM instance already up

**Comment by nilsnolde** [comment]
no idea if it has a health endpoint. just make a request.. http://project-osrm.org/docs/v5.23.0/api/

how are you running osrm? what is the failing request?

**Comment by AhtashamImtiyaz** [comment]
> I followed the steps and build my test in https://api-vroom.cr.onway.app/
> 
> But when I try with test request sometimes I got (using VROOM_ROUTER="ors"):
> 
> 2020-11-06T13:05:18.465245743Z Fri, 06 Nov 2020 13:05:18 GMT: [Error]
> 2020-11-06T13:05:18.465584149Z Fri, 06 Nov 2020 13:05:18 GMT: Failed to connect to 0.0.0.0:5000
> 2020-11-06T13:05:18.465862641Z Fri, 06 Nov 2020 13:05:18 GMT:
> 
> Changing enviroment variables and using (VROOM_ROUTER="osrm") I got:
> 
> 2020-11-06T13:12:49.048898242Z Fri, 06 Nov 2020 13:12:49 GMT: [Error]
> 2020-11-06T13:12:49.049249511Z Fri, 06 Nov 2020 13:12:49 GMT: Invalid profile: car.
> 2020-11-06T13:12:49.049500938Z Fri, 06 Nov 2020 13:12:49 GMT:
> 
> Any help?

You are receiving error because you need to install osrm locally or any external service or incase of ors, you can visit their website. And then in vehicles, you need to use the profile accordingly. If you dont specify a profile, VRoom will make it Car profile (its default in Vroom) but in docker, ors is default.

**Comment by renannery** [comment]
Not sure if related.

But I'm trying to deploy one image VROOM+ORS and I keep getting the following error when I'm testing the following request:
### Failed Request 
```
curl --location --request POST 'https://here-is-my-host.a.run.app' \
--header 'Content-Type: application/json' \
--data-raw '{
    "vehicles": [
        {
            "id": 0,
            "profile": "driving-car",
            "start": [
                2.3526,
                48.8604
            ],
            "end": [
                2.3526,
                48.8604
            ]
        }
    ],
    "jobs": [
        {
            "id": 0,
            "location": [
                2.3691,
                48.8532
            ]
        },
        {
            "id": 1,
            "location": [
                2.2911,
                48.8566
            ]
        }
    ],
    "options": {
        "g": true
    }
}'
```
### Failed Response
```
{
    "code": 3,
    "error": "Failed to connect to 0.0.0.0:8080"
}
```

Interestingly it works when I change the coordinates to something "closer"
### Success Request
```
curl --location --request POST 'https://vroom-3000-bqa4v2wf7a-uc.a.run.app' \
--header 'Content-Type: application/json' \
--data-raw '{
    "vehicles": [
        {
            "id": 0,
            "profile": "driving-car",
            "start": [
                -1,
                0
            ],
            "end": [
                -1,
                0
            ]
        }
    ],
    "jobs": [
        {
            "id": 0,
            "location": [
                -1,
                0
            ]
        },
        {
            "id": 1,
            "location": [
                -1,
                0
            ]
        }
    ]
}'
```
### Success Response
```
{
    "code": 0,
    "summary": {
        "cost": 0,
        "unassigned": 0,
        "service": 0,
        "duration": 0,
        "waiting_time": 0,
        "priority": 0,
        "computing_times": {
            "loading": 0,
            "solving": 0
        }
    },
.....
```
### docker-compose.yml
```
version: "2.4"
services:
  vroom:
    network_mode: host
    image: vroomvrp/vroom-docker:v1.8.0
    container_name: vroom
    volumes:
      - ./vroom-conf/:/conf
    environment:
      - VROOM_ROUTER=ors
    depends_on:
      - ors

  ors:
    container_name: ors
    ports:
      - 8080:8080
    image: openrouteservice/openrouteservice:latest
    volumes:
      - ./graphs:/ors-core/data/graphs
      - ./elevation_cache:/ors-core/data/elevation_cache
      - ./logs/ors:/var/log/ors
      - ./logs/tomcat:/usr/local/tomcat/logs
      - ./conf:/ors-conf
      - ./path/to/pbf/my_region_file.osm.pbf:/ors-core/data/osm_file.pbf
    environment:
      - BUILD_GRAPHS=False
      - "JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms2g -Xmx4g"
      - "CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"
```

## config.yml

I tried to change the host from `0.0.0.0` to `ors` based on other project but no luck

```
cliArgs:
  geometry: false # retrieve geometry (-g)
  threads: 4 # number of threads to use (-t)
  explore: 5 # exploration level to use (0..5) (-x)
  limit: "1mb" # max request size
  logdir: "/.." # the path for the logs relative to ./src
  maxlocations: 1000 # max number of jobs/shipments locations
  maxvehicles: 200 # max number of vehicles
  override: true # allow cli options override (-g, -t and -x)
  path: "" # VROOM path (if not in $PATH)
  port: 3000 # expressjs port
  router: "ors" # routing backend (osrm, libosrm or ors)
  timeout: 300000 # milli-seconds
  baseurl: "/" #base url for api
routingServers:
  ors:
    driving-car:
      host: "ors"
      port: "8080"
    driving-hgv:
      host: "ors"
      port: "8080"
    cycling-regular:
      host: "ors"
      port: "8080"
    cycling-mountain:
      host: "ors"
      port: "8080"
    cycling-road:
      host: "ors"
      port: "8080"
    cycling-electric:
      host: "ors"
      port: "8080"
    foot-walking:
      host: "ors"
      port: "8080"
    foot-hiking:
      host: "ors"
      port: "8080"
````

I'm basically composing `vroom-docker` with `docker-compose up --build --force-recreate -d` and pushing the image to my server. From my understanding, I don't need to push a different image of [ORS docker](https://github.com/GIScience/openrouteservice/tree/master/docker) and refer the external host on the `config.yml`.

Which would be something like:
```
ors:
    driving-car:
      host: "externalhost.net"
      port: "8080"
```

Would appreciate any help. Tks!
