### ISSUE TITLE
Self-hosted VROOM + ORS

### ISSUE THREAD

**Issue by renannery** [VROOM-Project/vroom-docker#27]
I've deployed successfully my ORS container
#### [GET] https://my-external-host-for-ORS.app/ors/v2/health
```
{
    "status": "ready"
}
```

I also have deployed successfully my VROOM container, but I got this error when submitting the request:
#### [POST] https://my-external-host-for-VROOM.app

```
{
    "code": 3,
    "error": "Failed to connect to 0.0.0.0:8080"
}
```

Note that they have different domain names, but they are running on the same server (Google Cloud Run) which I tested with a simple `ping -a https://my-external-host-for-ORS.app` and `ping -a https://my-external-host-for-VROOM.app` and the result is the same IP as expected.

One thing that is not clear for me is the usage of `network_mode: host`
`host` is just a flag or it should be the host address? i.e: `network_mode: https://my-external-host-for-ORS.app [or IP]` and since they are running on the same server, I believe `0.0.0.0:8080` should work, right?

Now I'm wondering which setting I'm missing in order to make VROOM and ORS communicate with each other, I'm pretty sure that might be something related to the networking setting.

Any help would be appreciated.

**Comment by renannery** [comment]
I also noticed that even changing the host address on `config.xml` to another IP, the error `Failed to connect to 0.0.0.0:8080` still the same, which makes me wonder if the file config.xml is been used or not.

**Comment by nilsnolde** [comment]
Sorry, a little late to the party.. 

I think there's a little confusion about networking with docker, maybe worth to read up. When you use docker-compose and you expect to use a private docker network (one where ports are not exposed on the host machine but services talk to each other in isolation), you'll need to use the name of the service in vroom's `config.yml` instead of `0.0.0.0` (for ORS by default `ors`, for OSRM `osrm`): 
https://github.com/VROOM-Project/vroom-docker/blob/8b2390df7eb95c5f90c41eb8986b02a3c7693d64/docker-compose.yml#L14
https://github.com/VROOM-Project/vroom-docker/blob/8b2390df7eb95c5f90c41eb8986b02a3c7693d64/docker-compose.yml#L31

I wanted to keep it simple (i.e. _not_ changing the `config.yml` created by a container) by setting  `network_mode: host` (and no, don't replace `host`, it's not meant to be your IP/domain but the word `host`) for vroom, which means the container only looks at the host machine for open ports, not inside any docker network. Which has the consequence that you can't configure the open port for vroom anymore (it'll just expose port 3000). But you don't have to change anything in any other file.

Really, the default docker-compose should just work out-of-the-box (commenting out at least one router..).

**Comment by DCSnip3r** [comment]
This makes sense to me now. I thought 'network-mode: host' would expose port 3000 but that needs to be configured via the first part of your comment. I might suggest adding "run the docker-compose" at the beginning of the readme instead of later on. As a docker newbie this was a little tricky to figure out

**Comment by nilsnolde** [comment]
networking in docker is a common pitfall in the beginning. I'll close this now. If anyone can offer better wording feel free to PR.

**Comment by robin-vjc** [comment]
I was confused by the instructions above; just to summarize for those encountering this issue:

In `docker-compose.yml`, comment out/delete `network_mode: host` and replace with:
```
version: "2.4"
services:
  vroom:
    ports:
      - 3000:3000
...
```
Then open `vroom-conf/config.yml` and (assuming OSRM is being used, and that `osrm` is the name of the service in `docker-compose.yml`) replace the `routingServers` section with:
```
routingServers:
  osrm:
    car:
      host: osrm
      port: '5000'
    bike:
      host: osrm
      port: '5000'
    foot:
      host: osrm
      port: '5000'
  ors:
...
```

**Comment by gwjacobs** [comment]
As an absolute novice at Docker I suffered for many hours trying to set up Vroom + openrouteservice and finally got my installation working. 

Here are the main things I needed to fix to get this to work:

1. ors and vroom must be on the same Docker network to talk to each other. You can do this in two ways:
  1. either start both containers separately, creating a new docker network via the `docker network create` command, and then connect both containers to the network using the `docker network connect` commend.
  2. even better, add vroom to the ORS docker-compose file. I added the following lines to my docker-compose file:

```
# ----------------- Vroom application configuration ------------------- #
  vroom:
    image: ghcr.io/vroom-project/vroom-docker:v1.14.0
    ports:
      - "3000:3000"
    volumes:
      - ./vroom-conf:/conf
    environment:
      VROOM_ROUTER: ors
```

2. The default port in the Vroom config file did not work for me. I had to change the port from 8080 to 8082. I troubleshooted the port by opening up a terminal within the Docker vroom container and running curl requests at the ors-app container until I found a port that connected - I'm sure there is a better way.
3. I also had to change the name of host to "ors-app" to match the name of my ORS docker container. In my Vroom config file I ended up with the following lines:

```
routingServers:
  ors:
    driving-car:
      # host: '0.0.0.0/ors/v2'
      # port: '8080'
      host: 'ors-app/ors/v2'
      port: '8082'
```

This gave me a giant amount of trouble but I now have Vroom and ORS running locally. For other novices, I highly recommend following the Docker tutorials and paying special attention to the "multi-container apps" tutorial. I really wanted to avoid having to learn Docker for this but it ended up helping me understand the issues I was facing.
