### ISSUE TITLE
Docker container mounting problem: Missing/Broken File

### ISSUE THREAD

**Issue by Shooter533** [VROOM-Project/vroom-docker#31]
Hi, I have a fresh ec2 instance t2 2xlarge running and have been trying to use docker to get the full stack running with docker-compose.

I'll be using OSRM so I have started with the following steps:
 
1. wget http://download.geofabrik.de/australia-oceania/australia-latest.osm.pbf
2. docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/australia-latest.osrm
3. docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-partition /data/australia-latest.osrm
4. docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-customize /data/australia-latest.osrm

These files all process with no errors.

I then  docker-compose up with my docker-compose.yml

`version: "2.4"
services:
  vroom:
        network_mode: host
        image: vroomvrp/vroom-docker:v1.8.0
        container_name: vroom
        volumes:
          - ./vroom-conf/:/conf
        environment:
          - VROOM_ROUTER=osrm  # router to use, osrm or ors
        depends_on:
          - osrm
  osrm:
      image: osrm/osrm-backend
      container_name: osrm
      restart: always
      ports:
        - 5000:5000
      volumes:
        - ./osrm:/data
      command: "osrm-routed --max-matching-size 1000 --max-table-size 1000 --max-viaroute-size 1000 --algorithm mld /data/australia-latest.osrm"`

I am getting an Missing/Broken File: /data/australia-latest.datasource_names and [error] Required files are missing, cannot continue.

I think this means that I have not correctly mounted the files inside my docker container, but as a docker newbie I don't know where I'm going wrong.

Any help

**Comment by jcoupey** [comment]
I don't think this has anything to do with `vroom` or even the Docker setup in this repo. The error you're seeing is an OSRM error.

>I think this means that I have not correctly mounted the files inside my docker container

Your own diagnosis is probably the right one. The OSRM GitHub bugtracker contains many issues with hints on how to do this.

**Comment by Shooter533** [comment]
Just found out that if I run it like this it works fine
`docker run -t -i -p 5000:5000 -v "${PWD}:/data" osrm/osrm-backend osrm-routed --algorithm mld /data/australia-latest.osrm`

But if I use the docker-compose up using the docker-compose.yml in this repo it fails

**Comment by Cichx** [comment]
Thanks for your post! 
I had exactly the same problem (Failed each time when trying to perform the setup according to the readme). Therefore, I thought it might be helpful to post a summarized Workaround.

**Workaround for installing VROOM+VROOM-Frontend+OSRM using Docker**
(Note: This workflow was tested on Linux, there seems to be some troubles on Windows)

1. Preprocess Data from [OSRM Website](https://hub.docker.com/r/osrm/osrm-backend/)
```
wget http://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/berlin-latest.osm.pbf
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-partition /data/berlin-latest.osrm
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-customize /data/berlin-latest.osrm
```

2. Clone VROOM-Docker repo 
`git clone https://github.com/VROOM-Project/vroom-docker.git`

3. Modify your `docker-compose.yml ` file according to your needs
In this case, change 
`/data/map.osrm`
to
`/data/berlin-latest.osrm`

4. Start OSRM and VROOM **seperately**! (According to the readme one would start it using `docker-compose up -d` but this seems to yield errors)
`docker run -t -i -p 5000:5000 -v "${PWD}:/data" osrm/osrm-backend osrm-routed --algorithm mld /data/berlin-latest.osrm`

To start the vroom docker I modified the `docker-compose.yml` and commented out all lines except:
```
version: "2.4"
services:
  vroom:
    network_mode: host
    image: vroomvrp/vroom-docker:v1.10.0
    container_name: vroom
    volumes:
      - ./vroom-conf/:/conf
    environment:
      - VROOM_ROUTER=osrm  # router to use, osrm, valhalla or ors
```
and started it using `docker-compose up -d`

5. Clone the Frontend Repo using
`git clone https://github.com/VROOM-Project/vroom-frontend.git`
and install it according to the [Readme](https://github.com/VROOM-Project/vroom-frontend) and run it using
`npm run serve`

Since I spend quite some time until everything was finally working, it thought this post might help.

**One remark:** 
If this Bug/Error continuous (eg. not fixed for the time being), it might be a good idea to make a short remark in the Readme of the VROOM-Docker repo ... otherwise people will wonder what in earth they're doing wrong if they perform the setup exactly as described and nothing is working^^.

**Comment by nilsnolde** [comment]
I didn't try it in a long time and not ever with OSRM. I'll try to find time one of these days and update here or the README. I'm still confused what's not supposed to work (what's the exact error)..

**Comment by Cichx** [comment]
I updated my comment, hopefully the error definition is a bit clearer now?

PS: I was using OSRM only because the [frontend-readme](https://github.com/VROOM-Project/vroom-frontend#requirements) said that it's only compatible with OSRM? Otherwise, I'd prefer Valhalla anyway ...

**Comment by nilsnolde** [comment]
I see. Can you share your docker-compose.yml, which OS you're on and a quick screenshot of the directory layout?

Valhalla has https://github.com/valhalla/demos, but that's not near as nice as osrm frontend, it's mostly for debugging. Other than that I published a QGIS plugin not tooo long ago: https://plugins.qgis.org/plugins/valhalla/.

**Comment by Cichx** [comment]
I use the "standard" docker-compose.yml from the repo, the OS is Ubuntu 20.04. Concerning the directory layout, I tried various constellations (e.g. extracting the OSRM data in different folders), none of them worked. Here's the layout of extracting the osrm data in vroom-docker/osrm/data (using the commands from my first post "1. Preprocess Data from OSRM Website")

```
:~/Documents/VROOM-Docker/vroom-docker/osrm/data$ ls
austria-latest.osm.pbf
austria-latest.osrm
austria-latest.osrm.cell_metrics
austria-latest.osrm.cells
austria-latest.osrm.cnbg
austria-latest.osrm.cnbg_to_ebg
austria-latest.osrm.datasource_names
austria-latest.osrm.ebg
austria-latest.osrm.ebg_nodes
austria-latest.osrm.edges
austria-latest.osrm.enw
austria-latest.osrm.fileIndex
austria-latest.osrm.geometry
austria-latest.osrm.icd
austria-latest.osrm.maneuver_overrides
austria-latest.osrm.mldgr
austria-latest.osrm.names
austria-latest.osrm.nbg_nodes
austria-latest.osrm.partition
austria-latest.osrm.properties
austria-latest.osrm.ramIndex
austria-latest.osrm.restrictions
austria-latest.osrm.timestamp
austria-latest.osrm.tld
austria-latest.osrm.tls
austria-latest.osrm.turn_duration_penalties
austria-latest.osrm.turn_penalties_index
austria-latest.osrm.turn_weight_penalties
init_OSRM.sh
```

**Comment by nilsnolde** [comment]
Ok, you will have to change the docker-compose, it can't know where your files are.

```
  osrm:
    image: osrm/osrm-backend
    container_name: osrm
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./osrm:/data
    command: "osrm-routed --max-matching-size 1000 --max-table-size 1000 --max-viaroute-size 1000 --algorithm mld /data/map.osrm"
```

if you used it exactly like that it indeed won't work. your files are in `./osrm/data` but the volume maps `./osrm` to the container's `/data` and also your file is not called `map.osrm` but austria-latest.osrm. 

Try this:
```
  osrm:
    image: osrm/osrm-backend
    container_name: osrm
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./osrm/data:/data
    command: "osrm-routed --max-matching-size 1000 --max-table-size 1000 --max-viaroute-size 1000 --algorithm mld /data/austria-latest.osrm"
```
