### ISSUE TITLE
Add OSRM to docker-compose.yml

### ISSUE THREAD

**Issue by nilsnolde** [VROOM-Project/vroom-docker#5]
ORS was easy for me. I'd appreciate if someone with OSRM experience (I never even set it up myself) could provide the example for OSRM.

**Comment by jcoupey** [comment]
Just to make sure I get this right, the purpose is to pull a pre-existing OSRM image independently? And this is the main difference from the work of @iedmrc at [https://github.com/iedmrc/vroom-docker](https://github.com/iedmrc/vroom-docker)?

**Comment by nilsnolde** [comment]
Exactly. OSRM already has its Dockerfile. Including it via `docker-compose` makes more sense IMHO, since you can swap with ORS (or Valhalla in close future) easily and the `vroom` image doesn't become dependent on OSRM.

Actually the integration seems to be easy, as it only requires to map a directory holding the PBF, OSRM Docker integration is a little poor, one can't even configure the port it should run on it seems. Maybe @iedmrc has a bit more experience with running it in Docker, but from what I see I can include it myself. Straight forward. Should've taken the 2 minutes it takes to read through the Docker readme;)

**Comment by mhosman** [comment]
You can attach domething like this to the docker-compose.yml (with the vroom container data).

```
    osrm:
        container_name: osrm
        image: osrm/osrm-backend
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - ./osrm:/data
        command: "osrm-routed --max-matching-size 1000 --max-table-size 1000 --max-viaroute-size 1000 --algorithm mld /data/map.osrm"
```

The only problem in my case is that I'm able to connect to both containers, buy I don't know why VROOM container is not able to connect to port 5000 of the osrm container.
