### ISSUE TITLE
VROOM + ORS Profile Mapping 

### ISSUE THREAD

**Issue by erdogansonmez** [VROOM-Project/vroom-docker#91]
### Docker Compose File
```yml
version: '3.8'
services:
  ors:
    image: openrouteservice/openrouteservice:latest
    container_name: ors
    ports:
      - "3400:8080"
    volumes:
      - ./ors:/home/ors
    environment:
      REBUILD_GRAPHS: "True" 
      CONTAINER_LOG_LEVEL: "DEBUG"
      XMS: 4g 
      XMX: 6g  
    networks:
      - ors-vroom-network

  vroom:
    image: ghcr.io/vroom-project/vroom-docker:latest
    container_name: vroom
    volumes:
      - ./vroom:/conf
    ports:
      - "6060:3000"
    networks:
      - ors-vroom-network

networks:
  ors-vroom-network:
    driver: bridge
```

### VROOM Config.yml

```yml
cliArgs:
  geometry: true # retrieve geometry (-g)
  planmode: false # run vroom in plan mode (-c) if set to true
  threads: 4 # number of threads to use (-t)
  explore: 5 # exploration level to use (0..5) (-x)
  limit: '1mb' # max request size
  logdir: '/..' # the path for the logs relative to ./src
  logsize: '100M' # max log file size for rotation
  maxlocations: 1000 # max number of jobs/shipments locations
  maxvehicles: 200 # max number of vehicles
  override: false # allow cli options override (-c, -g, -t and -x)
  path: '' # VROOM path (if not in $PATH)
  port: 3000 # expressjs port
  router: 'ors' # routing backend (osrm, libosrm or ors)
  timeout: 300000 # milli-seconds
  baseurl: '/' #base url for api
routingServers:
  ors:
    driving-car:
      host: 'ors/ors/v2'
      port: '8080'
```

### ORS ors-config.yml

```yml
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /ors
  tomcat:
    keep-alive-timeout: 30000

ors:
  services:
    optimization:
      enabled: true
      maximum_jobs: 500
      maximum_vehicles: 100
  engine:
    profile_default:
      build:
        source_file: /home/ors/files/turkey-latest.osm.pbf
    profiles:
      driving-car:
        enabled: true
  logging:
    level:
      root: INFO
      org.heigit: INFO

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
    tryItOutEnabled: true
    filter: false
    syntaxHighlight:
      activated: true
    showExtensions: true
  api-docs:
    path: /v2/api-docs
    version: OPENAPI_3_0
  packages-to-scan: org.heigit.ors
  pathsToMatch: /v2/**
```

## Curl
```bash
curl --location 'http://localhost:6060' \
--header 'Content-Type: application/json' \
--data '{
  "vehicles": [
    {
      "id": 1,
      "capacity": [5],
      "start": [36.890073275994644, 30.736684760656936]
    },
    {
      "id": 2,
      "capacity": [5],
      "start": [36.890073275994644, 30.736684760656936]
    }
  ],
  "jobs": [
    { "id": 1, "location": [36.890073275994644, 30.736684760656936] },
    { "id": 2, "location": [36.890073275994644, 30.736684760656936] },
    { "id": 3, "location": [36.890073275994644, 30.736684760656936] },
    { "id": 4, "location": [36.890073275994644, 30.736684760656936] },
    { "id": 5, "location": [36.890073275994644, 30.736684760656936] },
    { "id": 6, "location": [36.8805331, 30.7311783] }
  ],
  "depot": [36.890073275994644, 30.736684760656936], 
  "options": {
    "route_time": true 
  }
}'
```

## Problem

When i try send this request i got this response: 

> {"code":2,"error":"Invalid profile: car."}

I need to map profiles between vroom <-> ors. Vroom need 'car' profile, ors need 'driving-car' profile.

**Comment by erdogansonmez** [comment]
I looked vroom-express source code, so i think mapping not possible for now. I did mapping from ORS side like this.

## ors-config.yml
```yml
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /ors
  tomcat:
    keep-alive-timeout: 30000

ors:
  services:
    optimization:
      enabled: true
      maximum_jobs: 500
      maximum_vehicles: 100
  engine:
    profile_default:
      build:
        source_file: /home/ors/files/turkey-latest.osm.pbf
    profiles:
      car:
        enabled: true
        encoder_name: driving-car
        build:
          encoder_options:
            turn_costs: true
            block_fords: false
            use_acceleration: true
          preparation:
            min_network_size: 200
            methods:
              ch:
                enabled: true
                threads: 1
                weightings: fastest
              lm:
                enabled: false
              core:
                enabled: true
                threads: 1
                weightings: fastest,shortest
                landmarks: 64
                lmsets: highways;allow_all
          ext_storages:
            WayCategory:
            HeavyVehicle:
            Tollways:
            WaySurfaceType:
            RoadAccessRestrictions:
              use_for_warnings: true
        service:
          execution:
            methods:
              lm:
                active_landmarks: 6
              core:
                active_landmarks: 6
  logging:
    level:
      root: INFO
      org.heigit: INFO

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
    tryItOutEnabled: true
    filter: false
    syntaxHighlight:
      activated: true
    showExtensions: true
  api-docs:
    path: /v2/api-docs
    version: OPENAPI_3_0
  packages-to-scan: org.heigit.ors
  pathsToMatch: /v2/**
```
